openapi: 3.0.0
info:
  title: Photo Rating API
  version: 1.0.0
paths:
  /api/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                  user:
                    type: object
        '400':
          description: Email already registered
        '500':
          description: Registration failed
  /api/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                  user:
                    type: object
        '400':
          description: Invalid credentials
        '404':
          description: User not found
        '500':
          description: Login failed
  /api/photos/upload:
    post:
      summary: Upload a photo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
      responses:
        '201':
          description: Photo uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  photo:
                    type: object
        '400':
          description: No file uploaded
        '500':
          description: File upload failed
  /api/photos/{photoId}/toggle-active:
    put:
      summary: Toggle photo active status
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: photoId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Photo status updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  photo:
                    type: object
        '403':
          description: Not enough points to activate photo
        '404':
          description: Photo not found or not owned by user
        '500':
          description: Failed to toggle photo status
  /api/photos/rating:
    get:
      summary: Get photos for rating
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of active photos for rating
          content:
            application/json:
              schema:
                type: object
                properties:
                  photos:
                    type: array
                    items:
                      type: object
        '500':
          description: Failed to fetch photos for rating
  /api/photos/my:
    get:
      summary: Get user's photos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user's photos
          content:
            application/json:
              schema:
                type: object
                properties:
                  photos:
                    type: array
                    items:
                      type: object
        '500':
          description: Failed to fetch user photos
  /api/photos/{photoId}/stats:
    get:
      summary: Get photo statistics
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: photoId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Photo statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  stats:
                    type: object
                    properties:
                      totalRatings:
                        type: number
                      averageScore:
                        type: number
                      byGender:
                        type: object
                      byAge:
                        type: object
        '404':
          description: Photo not found or not owned by user
        '500':
          description: Failed to fetch photo statistics
  /api/ratings:
    post:
      summary: Rate a photo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
                score:
                  type: number
      responses:
        '201':
          description: Photo rated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  rating:
                    type: object
        '403':
          description: Cannot rate own photo or already rated
        '404':
          description: Photo not found
        '500':
          description: Failed to rate photo
  /api/ratings/my:
    get:
      summary: Get user's ratings
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user's ratings
          content:
            application/json:
              schema:
                type: object
                properties:
                  ratings:
                    type: array
                    items:
                      type: object
        '500':
          description: Failed to fetch user ratings
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
